blank_issues_enabled: true
contact_links:
  - name: Report an issue
    url: https://github.com/Nedevski/py_kat_bulgaria/issues/new
    about: If you use this library standalone, please open an issue here
  - name: Report a bug with the "KAT Bulgaria" HACS (Home Assistant) integration
    url: https://github.com/Nedevski/hass_kat_bulgaria/issues/new/choose
    about: If you have a problem with the "KAT Bulgaria" integration in HACS (Home Assistant), please report issues in its own repo
